version: '3.1'
services:
  main-service:
    build: explore-with-me-main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8081:8080"
    depends_on:
      - stats-server
      - main-service-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-service-db:5432/servicedb
      - SPRING_DATASOURCE_USERNAME=service_admin
      - SPRING_DATASOURCE_PASSWORD=adm1n
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  main-service-db:
    image: postgres:14-alpine
    container_name: main-service-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=adm1n
      - POSTGRES_USER=service_admin
      - POSTGRES_DB=servicedb

  stats-server:
    build: explore-with-me-stats-service/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9091:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=stats_admin
      - SPRING_DATASOURCE_PASSWORD=s1ats
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=s1ats
      - POSTGRES_USER=stats_admin
      - POSTGRES_DB=statsdb

