create table if not exists users (
    id bigint generated by default as identity,
    name varchar(250),
    email varchar(254),
    constraint pk_user primary key (id),
    constraint UQ_USER_EMAIL unique (email)
);

create table if not exists categories (
    id bigint generated by default as identity,
    name varchar(50),
    constraint pk_categories primary key (id),
    constraint UQ_CATEGORY_NAME unique (name)
);

create table if not exists events (
    id bigint generated by default as identity,
    title varchar(120) not null,
    annotation varchar(2000),
    description varchar(7000) not null,
    cat_id bigint references categories (id) not null,
    participant_limit int not null,
    state varchar(20) not null,
    paid boolean not null,
    event_date timestamp not null,
    created_on timestamp not null,
    published_on timestamp,
    initiator_id bigint references users (id) not null,
    latitude float not null,
    lontitude float not null,
    req_moderation boolean not null,
    constraint pk_events primary key (id)
);

create table if not exists participation_requests (
    id bigint generated by default as identity,
    requester_id bigint references users (id),
    event_id bigint references events (id),
    status varchar(50) not null,
    created timestamp not null,
    constraint pk_participation_requests primary key (id),
    constraint UQ_PARTICIPANT_PER_EVENT unique (requester_id, event_id)
);

create table if not exists compilations (
    id bigint generated by default as identity,
    title varchar(120),
    pinned boolean not null,
    constraint pk_compilations primary key (id)
);

create table if not exists compilation_of_events (
    comp_id bigint references compilations (id) not null,
    event_id bigint references events (id) not null,
    constraint pk_compilation_of_events primary key (comp_id, event_id)
);

create table if not exists comments (
    id bigint generated by default as identity,
    text varchar(1000) not null,
    created_on timestamp not null,
    event_id bigint references events (id),
    user_id bigint references users (id),
    constraint UQ_COMMENT_PER_EVENT unique (user_id, event_id)
)